(() => {
  const locale = (document.documentElement.lang || 'en').split('-')[0];
  const order = ['uz', 'tg', 'es', 'id'];
  const rows = [
    ['Home','Bosh sahifa','Асосӣ','Inicio','Beranda'],['Articles','Maqolalar','Мақолаҳо','Artículos','Artikel'],['← Back home','← Bosh sahifaga','← Ба саҳифаи асосӣ','← Volver al inicio','← Kembali ke beranda'],
    ['Game mathematics laboratory','O‘yin matematikasi laboratoriyasi','Озмоишгоҳи математикаи бозӣ','Laboratorio de matemática de juegos','Laboratorium matematika game'],['Probability laboratory','Ehtimollik laboratoriyasi','Озмоишгоҳи эҳтимолият','Laboratorio de probabilidades','Laboratorium probabilitas'],['Basic strategy trainer','Asosiy strategiya trenajyori','Тренажёри стратегияи асосӣ','Entrenador de estrategia básica','Pelatih strategi dasar'],

    ['Slot RTP & Volatility Simulator — Gamer Logic Hub','Slot RTP va volatillik simulyatori — Gamer Logic Hub','Симулятори RTP ва ноустувории слотҳо — Gamer Logic Hub','Simulador de RTP y volatilidad de slots — Gamer Logic Hub','Simulator RTP & volatilitas slot — Gamer Logic Hub'],
    ['Slot RTP & Volatility Lab','Slot RTP va volatillik laboratoriyasi','Озмоишгоҳи RTP ва ноустувории слотҳо','Laboratorio de RTP y volatilidad de slots','Laboratorium RTP & volatilitas slot'],
    ['RTP · volatility · randomness','RTP · volatillik · tasodifiylik','RTP · ноустуворӣ · тасодуф','RTP · volatilidad · azar','RTP · volatilitas · keacakan'],
    ['Configure a mathematical model and see why the observed return of a short session almost never matches the theoretical RTP.','Matematik modelni sozlang va qisqa sessiyaning amaldagi qaytimi nega deyarli hech qachon nazariy RTPga teng bo‘lmasligini ko‘ring.','Модели математикиро танзим карда, бинед, ки чаро бозгашти воқеии ҷаласаи кӯтоҳ қариб ҳеҷ гоҳ ба RTP-и назариявӣ баробар намешавад.','Configurá el modelo matemático y observá por qué el retorno real de una sesión corta casi nunca coincide con el RTP teórico.','Atur model matematika dan lihat mengapa pengembalian aktual sesi singkat hampir tidak pernah sama dengan RTP teoretis.'],
    ['Model settings','Model sozlamalari','Танзимоти модел','Parámetros del modelo','Pengaturan model'],['Theoretical RTP','Nazariy RTP','RTP-и назариявӣ','RTP teórico','RTP teoretis'],['Volatility','Volatillik','Ноустуворӣ','Volatilidad','Volatilitas'],['Low','Past','Паст','Baja','Rendah'],['Medium','O‘rtacha','Миёна','Media','Sedang'],['High','Yuqori','Баланд','Alta','Tinggi'],['Number of spins','Aylantirishlar soni','Шумораи гардишҳо','Cantidad de giros','Jumlah putaran'],['Bet per spin','Har aylantirish uchun miqdor','Миқдор барои ҳар гардиш','Cantidad por giro','Jumlah per putaran'],['Run experiment','Tajribani boshlash','Озмоишро оғоз кардан','Realizar experimento','Jalankan eksperimen'],['Reset results','Natijalarni tiklash','Натиҷаҳоро аз нав кардан','Restablecer resultados','Atur ulang hasil'],
    ['This is a demonstration model. Payouts are generated from a distribution calibrated to the selected RTP; it does not reproduce any commercial slot.','Bu namoyish modeli. To‘lovlar tanlangan RTPga moslangan taqsimotdan yaratiladi; model hech qanday tijoriy slotni takrorlamaydi.','Ин модели намоишӣ аст. Пардохтҳо аз тақсимоте сохта мешаванд, ки ба RTP-и интихобшуда мутобиқ шудааст; он ягон слоти тиҷориро такрор намекунад.','Este es un modelo demostrativo. Los pagos se generan con una distribución ajustada al RTP elegido; no reproduce ningún slot comercial.','Ini adalah model demonstrasi. Pembayaran dihasilkan dari distribusi yang disesuaikan dengan RTP pilihan; model ini tidak meniru slot komersial mana pun.'],
    ['Observed RTP','Amaldagi RTP','RTP-и воқеӣ','RTP observado','RTP aktual'],['Session result','Sessiya natijasi','Натиҷаи ҷаласа','Resultado de la sesión','Hasil sesi'],['Hit frequency','Yutuqlar chastotasi','Басомади бурдҳо','Frecuencia de premios','Frekuensi kemenangan'],['Maximum drawdown','Maksimal pasayish','Коҳиши максималӣ','Caída máxima','Penurunan maksimum'],['Payout distribution','To‘lovlar taqsimoti','Тақсимоти пардохтҳо','Distribución de pagos','Distribusi pembayaran'],['The bars show how often a result landed in each multiplier range.','Ustunlar natija har bir ko‘paytirgich oralig‘iga qanchalik tez-tez tushganini ko‘rsatadi.','Сутунҳо нишон медиҳанд, ки натиҷа ба ҳар як диапазони зарбкунанда чанд бор афтодааст.','Las barras muestran con qué frecuencia el resultado cayó en cada rango de multiplicadores.','Batang menunjukkan seberapa sering hasil masuk ke setiap rentang pengali.'],['Choose the settings and run your first experiment.','Sozlamalarni tanlang va birinchi tajribani boshlang.','Танзимотро интихоб карда, озмоиши аввалро оғоз кунед.','Elegí los parámetros e iniciá el primer experimento.','Pilih pengaturan dan jalankan eksperimen pertama.'],
    ['What the lab demonstrates','Laboratoriya nimani ko‘rsatadi','Озмоишгоҳ чиро нишон медиҳад','Qué muestra el laboratorio','Apa yang ditunjukkan laboratorium'],['is the theoretical share of all stakes returned over a very large sample. Volatility describes the payout pattern: frequent small results or rare large ones.','— juda katta tanlanmada qaytariladigan barcha miqdorlarning nazariy ulushi. Volatillik to‘lovlar xususiyatini ifodalaydi: tez-tez uchraydigan kichik natijalar yoki kam uchraydigan yirik natijalar.','— ҳиссаи назариявии ҳамаи маблағҳоест, ки дар фосилаи хеле дароз бармегардад. Ноустуворӣ шакли пардохтҳоро тавсиф мекунад: натиҷаҳои хурди зуд-зуд ё натиҷаҳои калони нодир.','es la proporción teórica de todas las cantidades que vuelve en una muestra muy grande. La volatilidad describe el patrón de pagos: resultados pequeños frecuentes o grandes poco frecuentes.','adalah bagian teoretis dari seluruh jumlah yang kembali dalam sampel sangat besar. Volatilitas menggambarkan pola pembayaran: hasil kecil yang sering atau hasil besar yang jarang.'],['Why do results differ?','Nega natijalar farq qiladi?','Чаро натиҷаҳо фарқ мекунанд?','¿Por qué difieren los resultados?','Mengapa hasilnya berbeda?'],['Every spin is independent. Random deviation can be large over 100 or 1,000 trials. A larger sample generally moves the observed RTP closer to the target, but never guarantees an exact match.','Har bir aylantirish mustaqil. 100 yoki 1 000 ta sinovda tasodifiy og‘ish katta bo‘lishi mumkin. Kattaroq tanlanma odatda amaldagi RTPni maqsadga yaqinlashtiradi, ammo aniq moslikni kafolatlamaydi.','Ҳар гардиш мустақил аст. Дар 100 ё 1 000 озмоиш инҳирофи тасодуфӣ метавонад калон бошад. Намунаи калонтар одатан RTP-и воқеиро ба ҳадаф наздик мекунад, аммо мувофиқати дақиқро кафолат намедиҳад.','Cada giro es independiente. En 100 o 1.000 pruebas, el desvío aleatorio puede ser grande. Una muestra mayor suele acercar el RTP observado al objetivo, pero nunca garantiza una coincidencia exacta.','Setiap putaran bersifat independen. Penyimpangan acak dapat besar dalam 100 atau 1.000 percobaan. Sampel yang lebih besar biasanya mendekatkan RTP aktual ke target, tetapi tidak menjamin kecocokan persis.'],['Educational model only. No real money, wagering or prizes are involved.','Faqat ta’limiy model. Haqiqiy pul, tikish yoki sovrinlar ishlatilmaydi.','Танҳо модели омӯзишӣ. Пули воқеӣ, шарт ё ҷоиза истифода намешавад.','Solo es un modelo educativo. No se usa dinero real, apuestas ni premios.','Hanya model edukatif. Tidak menggunakan uang sungguhan, taruhan, atau hadiah.'],
    ['Free RTP and volatility lab: run up to 100,000 virtual spins and compare theoretical RTP with the observed result.','Bepul RTP va volatillik laboratoriyasi: 100 000 tagacha virtual aylantirish o‘tkazing va nazariy RTPni amaldagi natija bilan solishtiring.','Озмоишгоҳи ройгони RTP ва ноустуворӣ: то 100 000 гардиши виртуалӣ гузаронед ва RTP-и назариявиро бо натиҷаи воқеӣ муқоиса кунед.','Laboratorio gratis de RTP y volatilidad: realizá hasta 100.000 giros virtuales y compará el RTP teórico con el resultado observado.','Laboratorium RTP dan volatilitas gratis: jalankan hingga 100.000 putaran virtual dan bandingkan RTP teoretis dengan hasil aktual.'],['Explore spins, RTP, volatility and drawdown without real money.','Aylantirishlar, RTP, volatillik va pasayishni haqiqiy pulsiz o‘rganing.','Гардишҳо, RTP, ноустуворӣ ва коҳишро бе пули воқеӣ омӯзед.','Explorá giros, RTP, volatilidad y caídas sin dinero real.','Pelajari putaran, RTP, volatilitas, dan penurunan tanpa uang sungguhan.'],['Payout distribution histogram','To‘lovlar taqsimoti gistogrammasi','Гистограммаи тақсимоти пардохтҳо','Histograma de distribución de pagos','Histogram distribusi pembayaran'],['Slot Lab — RTP & Volatility Simulator','Slot Lab — RTP va volatillik simulyatori','Slot Lab — симулятори RTP ва ноустуворӣ','Slot Lab — simulador de RTP y volatilidad','Slot Lab — simulator RTP dan volatilitas'],

    ['Roulette Simulator & Odds Calculator','Ruletka simulyatori va ehtimollik kalkulyatori','Симулятори рулетка ва ҳисобкунаки эҳтимолият','Simulador de ruleta y calculadora de probabilidades','Simulator roulette & kalkulator peluang'],
    ['Roulette Simulator & Odds Calculator — Gamer Logic Hub','Ruletka simulyatori va ehtimollik kalkulyatori — Gamer Logic Hub','Симулятори рулетка ва ҳисобкунаки эҳтимолият — Gamer Logic Hub','Simulador de ruleta y calculadora de probabilidades — Gamer Logic Hub','Simulator roulette & kalkulator peluang — Gamer Logic Hub'],['Probability · payouts · house edge','Ehtimollik · to‘lovlar · platforma ustunligi','Эҳтимолият · пардохтҳо · бартарии хона','Probabilidad · pagos · ventaja de la casa','Probabilitas · pembayaran · keunggulan rumah'],['Choose a wheel and bet, see the exact odds, then test them with one spin or a larger sample.','G‘ildirak va shartli tanlovni belgilang, aniq ehtimolliklarni ko‘ring, so‘ng ularni bitta aylantirish yoki katta tanlanmada tekshiring.','Навъи чарх ва интихоби шартиро муайян карда, эҳтимолияти дақиқро бинед ва онро бо як гардиш ё намунаи калонтар санҷед.','Elegí una rueda y una opción, consultá las probabilidades exactas y después probalas con un giro o una muestra mayor.','Pilih roda dan opsi, lihat peluang tepatnya, lalu uji dengan satu putaran atau sampel yang lebih besar.'],['Experiment settings','Tajriba sozlamalari','Танзимоти озмоиш','Configuración del experimento','Pengaturan eksperimen'],['Roulette type','Ruletka turi','Навъи рулетка','Tipo de ruleta','Jenis roulette'],['European','Yevropa','Аврупоӣ','Europea','Eropa'],['American','Amerika','Амрикоӣ','Americana','Amerika'],['Virtual stake','Shartli miqdor','Миқдори шартӣ','Cantidad virtual','Jumlah virtual'],['Spins per run','Seriyadagi aylantirishlar','Гардишҳо дар силсила','Giros por serie','Putaran per seri'],['Run series','Seriyani boshlash','Силсиларо оғоз кардан','Iniciar serie','Jalankan seri'],['Clear results','Natijalarni tozalash','Натиҷаҳоро пок кардан','Borrar resultados','Hapus hasil'],
    ['Standard return-inclusive multipliers are used. Probability and house edge update automatically when the wheel type changes.','Stavka qaytimini o‘z ichiga olgan standart ko‘paytirgichlar ishlatiladi. G‘ildirak turi o‘zgarganda ehtimollik va platforma ustunligi avtomatik qayta hisoblanadi.','Зарбкунандаҳои стандартӣ бо баргардонидани маблағ истифода мешаванд. Ҳангоми тағйири навъи чарх эҳтимолият ва бартарии хона худкор аз нав ҳисоб мешаванд.','Se usan multiplicadores estándar que incluyen la devolución. La probabilidad y la ventaja de la casa se actualizan automáticamente al cambiar la rueda.','Pengali standar yang mencakup pengembalian digunakan. Probabilitas dan keunggulan rumah diperbarui otomatis saat jenis roda berubah.'],['Probability','Ehtimollik','Эҳтимолият','Probabilidad','Probabilitas'],['Payout','To‘lov','Пардохт','Pago','Pembayaran'],['House edge','Platforma ustunligi','Бартарии хона','Ventaja de la casa','Keunggulan rumah'],['Last number','So‘nggi raqam','Рақами охирин','Último número','Angka terakhir'],['Choose a bet','Tanlovni belgilang','Интихобро муайян кунед','Elegí una opción','Pilih opsi'],['Select one bet per experiment to compare probabilities cleanly.','Ehtimolliklarni aniq solishtirish uchun har tajribada bitta tanlovni belgilang.','Барои муқоисаи дақиқи эҳтимолиятҳо дар ҳар озмоиш як интихобро муайян кунед.','Elegí una sola opción por experimento para comparar bien las probabilidades.','Pilih satu opsi per eksperimen agar probabilitas dapat dibandingkan dengan jelas.'],
    ['Red','Qizil','Сурх','Rojo','Merah'],['Black','Qora','Сиёҳ','Negro','Hitam'],['Even','Juft','Ҷуфт','Par','Genap'],['Odd','Toq','Тоқ','Impar','Ganjil'],['1st dozen','1-o‘nlik','Даҳгонаи 1','1.ª docena','Lusin pertama'],['2nd dozen','2-o‘nlik','Даҳгонаи 2','2.ª docena','Lusin kedua'],['3rd dozen','3-o‘nlik','Даҳгонаи 3','3.ª docena','Lusin ketiga'],['Column 1','1-ustun','Сутуни 1','Columna 1','Kolom 1'],['Column 2','2-ustun','Сутуни 2','Columna 2','Kolom 2'],['Column 3','3-ustun','Сутуни 3','Columna 3','Kolom 3'],['Zero','Nol','Сифр','Cero','Nol'],['Number…','Raqam…','Рақам…','Número…','Angka…'],['Number','Raqam','Рақам','Número','Angka'],['Hits','Tushishlar','Бурдҳо','Aciertos','Kena'],['Misses','Tushmasliklar','Бохтҳо','Fallos','Meleset'],['Observed frequency','Amaldagi chastota','Басомади воқеӣ','Frecuencia observada','Frekuensi aktual'],['Choose a bet and run a series.','Tanlovni belgilang va seriyani boshlang.','Интихобро муайян карда, силсиларо оғоз кунед.','Elegí una opción e iniciá una serie.','Pilih opsi dan jalankan seri.'],
    ['European vs American roulette','Yevropa va Amerika ruletkasi','Рулеткаи аврупоӣ ва амрикоӣ','Ruleta europea y americana','Roulette Eropa dan Amerika'],['A European wheel has 37 pockets: numbers 1–36 and one zero. An American wheel has 38 because it adds 00. With the same payouts, the second zero raises the house edge from 2.70% to 5.26% on most bets.','Yevropa g‘ildiragida 37 ta sektor bor: 1–36 raqamlari va bitta nol. Amerika g‘ildiragida qo‘shimcha 00 sababli 38 ta sektor bor. Bir xil to‘lovlarda ikkinchi nol aksariyat tanlovlar uchun platforma ustunligini 2,70% dan 5,26% gacha oshiradi.','Чархи аврупоӣ 37 бахш дорад: рақамҳои 1–36 ва як сифр. Чархи амрикоӣ бо сабаби 00-и иловагӣ 38 бахш дорад. Бо пардохтҳои якхела сифри дуюм бартарии хонаро барои аксари интихобҳо аз 2,70% то 5,26% зиёд мекунад.','La rueda europea tiene 37 casillas: los números del 1 al 36 y un cero. La americana tiene 38 porque agrega el 00. Con los mismos pagos, el segundo cero aumenta la ventaja de la casa del 2,70% al 5,26% en la mayoría de las opciones.','Roda Eropa memiliki 37 kantong: angka 1–36 dan satu nol. Roda Amerika memiliki 38 karena menambahkan 00. Dengan pembayaran yang sama, nol kedua menaikkan keunggulan rumah dari 2,70% menjadi 5,26% untuk sebagian besar opsi.'],['Results are independent: previous numbers do not change the probability of the next spin.','Natijalar mustaqil: oldingi raqamlar keyingi aylantirish ehtimoliga ta’sir qilmaydi.','Натиҷаҳо мустақиланд: рақамҳои қаблӣ эҳтимолияти гардиши навбатиро тағйир намедиҳанд.','Los resultados son independientes: los números anteriores no cambian la probabilidad del próximo giro.','Setiap hasil independen: angka sebelumnya tidak mengubah probabilitas putaran berikutnya.'],['A mathematical demonstration using virtual points, with no monetary wagering or prizes.','Virtual ballardan foydalanadigan matematik namoyish; pul tikish yoki sovrinlar yo‘q.','Намоиши математикӣ бо холҳои виртуалӣ, бе шартҳои пулӣ ё ҷоизаҳо.','Una demostración matemática con puntos virtuales, sin apuestas de dinero ni premios.','Demonstrasi matematika dengan poin virtual, tanpa taruhan uang atau hadiah.'],
    ['Free European and American roulette simulator: compare probability, payout and house edge, then run a series of spins.','Bepul Yevropa va Amerika ruletkasi simulyatori: ehtimollik, to‘lov va platforma ustunligini solishtiring, so‘ng aylantirishlar seriyasini boshlang.','Симулятори ройгони рулеткаи аврупоӣ ва амрикоӣ: эҳтимолият, пардохт ва бартарии хонаро муқоиса карда, силсилаи гардишҳоро гузаронед.','Simulador gratis de ruleta europea y americana: compará probabilidad, pago y ventaja de la casa, y después realizá una serie de giros.','Simulator roulette Eropa dan Amerika gratis: bandingkan probabilitas, pembayaran, dan keunggulan rumah, lalu jalankan serangkaian putaran.'],['Build a bet and compare European and American roulette at a glance.','Tanlov tuzing va Yevropa hamda Amerika ruletkasini ko‘rgazmali solishtiring.','Интихоб созед ва рулеткаи аврупоӣ ва амрикоиро ба таври аёнӣ муқоиса кунед.','Armá una opción y compará visualmente la ruleta europea y la americana.','Buat opsi dan bandingkan roulette Eropa dan Amerika secara langsung.'],['Roulette Lab — Simulator & Odds Calculator','Roulette Lab — simulyator va ehtimollik kalkulyatori','Roulette Lab — симулятор ва ҳисобкунаки эҳтимолият','Roulette Lab — simulador y calculadora de probabilidades','Roulette Lab — simulator dan kalkulator peluang'],

    ['Blackjack Basic Strategy Trainer — Gamer Logic Hub','Blackjack asosiy strategiya trenajyori — Gamer Logic Hub','Тренажёри стратегияи асосии Blackjack — Gamer Logic Hub','Entrenador de estrategia básica de Blackjack — Gamer Logic Hub','Pelatih strategi dasar Blackjack — Gamer Logic Hub'],['Decisions · rules · practice','Qarorlar · qoidalar · mashq','Қарорҳо · қоидаҳо · машқ','Decisiones · reglas · práctica','Keputusan · aturan · latihan'],['Choose an action for each deal and immediately learn whether it matches basic strategy for the selected rules.','Har bir tarqatish uchun harakatni tanlang va u belgilangan qoidalardagi asosiy strategiyaga mos kelishini darhol biling.','Барои ҳар тақсимот амалеро интихоб карда, фавран фаҳмед, ки он ба стратегияи асосии қоидаҳои интихобшуда мувофиқ аст ё не.','Elegí una acción para cada mano y descubrí al instante si coincide con la estrategia básica para las reglas seleccionadas.','Pilih tindakan untuk setiap pembagian dan langsung ketahui apakah sesuai dengan strategi dasar untuk aturan yang dipilih.'],['Table rules','Stol qoidalari','Қоидаҳои миз','Reglas de la mesa','Aturan meja'],['Number of decks','Kolodalar soni','Шумораи дастаҳо','Cantidad de mazos','Jumlah dek'],['1 deck','1 koloda','1 даста','1 mazo','1 dek'],['6 decks','6 koloda','6 даста','6 mazos','6 dek'],['8 decks','8 koloda','8 даста','8 mazos','8 dek'],['Dealer on soft 17','Diler yumshoq 17 da','Дилер дар 17-и нарм','Crupier con 17 blando','Dealer pada soft 17'],['Stands','To‘xtaydi','Меистад','Se planta','Berhenti'],['Double after split','Bo‘lishdan keyin ikkilash','Дучандкунӣ пас аз тақсим','Doblar después de separar','Gandakan setelah split'],['Yes','Ha','Ҳа','Sí','Ya'],['No','Yo‘q','Не','No','Tidak'],['New situation','Yangi vaziyat','Вазъияти нав','Nueva situación','Situasi baru'],['Reset statistics','Statistikani tiklash','Оморро аз нав кардан','Restablecer estadísticas','Atur ulang statistik'],
    ["Basic strategy reduces the casino's mathematical edge, but it cannot predict cards or guarantee a win on any deal.",'Asosiy strategiya kazino matematik ustunligini kamaytiradi, ammo kartalarni oldindan aytmaydi va hech bir tarqatishda g‘alabani kafolatlamaydi.','Стратегияи асосӣ бартарии математикии казиноро кам мекунад, аммо кортҳоро пешгӯӣ намекунад ва дар ягон тақсимот бурдро кафолат намедиҳад.','La estrategia básica reduce la ventaja matemática del casino, pero no puede predecir las cartas ni garantizar una victoria en ninguna mano.','Strategi dasar mengurangi keunggulan matematis kasino, tetapi tidak dapat memprediksi kartu atau menjamin kemenangan dalam pembagian apa pun.'],['Correct decisions','Qarorlar to‘g‘ri','Қарорҳои дуруст','Decisiones correctas','Keputusan benar'],['Mistakes','Xatolar','Хатоҳо','Errores','Kesalahan'],['Accuracy','Aniqlik','Дақиқӣ','Precisión','Akurasi'],['Streak','Seriya','Силсила','Racha','Rentetan'],['What would you do?','Qanday yo‘l tutasiz?','Шумо чӣ кор мекардед?','¿Qué harías?','Apa tindakan Anda?'],["The dealer's upcard is shown above. Evaluate your hand and choose an action.",'Dilerning ochiq kartasi yuqorida. Qo‘lingizni baholang va harakatni tanlang.','Корти кушодаи дилер дар боло аст. Дасти худро арзёбӣ карда, амалеро интихоб кунед.','La carta visible del crupier está arriba. Evaluá tu mano y elegí una acción.','Kartu terbuka dealer ditampilkan di atas. Nilai kartu Anda dan pilih tindakan.'],['Dealer','Diler','Дилер','Crupier','Dealer'],['Your hand','Qo‘lingiz','Дасти шумо','Tu mano','Kartu Anda'],['Hit','Karta olish','Корт гирифтан','Pedir','Ambil'],['Stand','To‘xtash','Истодан','Plantarse','Berhenti'],['Double','Ikkilash','Дучанд кардан','Doblar','Gandakan'],['Split','Bo‘lish','Тақсим кардан','Separar','Split'],['Study the cards and choose an action.','Kartalarni o‘rganing va harakatni tanlang.','Кортҳоро омӯзед ва амалеро интихоб кунед.','Estudiá las cartas y elegí una acción.','Pelajari kartu dan pilih tindakan.'],
    ['How the trainer works','Trenajyor qanday ishlaydi','Тренажёр чӣ гуна кор мекунад','Cómo funciona el entrenador','Cara kerja pelatih'],['The recommendation follows a basic strategy table for European late-hole-card rules. The trainer distinguishes hard hands, soft ace hands and pairs.','Tavsiya yopiq karta kech tekshiriladigan Yevropa qoidalari uchun asosiy strategiya jadvaliga asoslanadi. Trenajyor qattiq qo‘llar, tuzli yumshoq qo‘llar va juftlarni ajratadi.','Тавсия ба ҷадвали стратегияи асосӣ барои қоидаҳои аврупоӣ бо санҷиши дерини корти пӯшида асос ёфтааст. Тренажёр дастҳои сахт, дастҳои нарм бо туз ва ҷуфтҳоро фарқ мекунад.','La recomendación sigue una tabla de estrategia básica para reglas europeas con verificación tardía de la carta oculta. El entrenador distingue manos duras, manos blandas con as y pares.','Rekomendasi mengikuti tabel strategi dasar untuk aturan Eropa dengan pemeriksaan kartu tertutup yang terlambat. Pelatih membedakan kartu keras, kartu lunak dengan ace, dan pasangan.'],['S17/H17 and DAS settings affect borderline decisions. At a real table, the exact chart also depends on surrender, hole-card checks and other rules.','S17/H17 va DAS sozlamalari chegaraviy qarorlarga ta’sir qiladi. Haqiqiy stolda aniq jadval surrender, yopiq kartani tekshirish va boshqa qoidalarga ham bog‘liq.','Танзимоти S17/H17 ва DAS ба қарорҳои сарҳадӣ таъсир мекунанд. Дар мизи воқеӣ ҷадвали дақиқ инчунин аз surrender, санҷиши корти пӯшида ва қоидаҳои дигар вобаста аст.','Las opciones S17/H17 y DAS afectan las decisiones límite. En una mesa real, la tabla exacta también depende del surrender, la verificación de la carta oculta y otras reglas.','Pengaturan S17/H17 dan DAS memengaruhi keputusan batas. Di meja nyata, tabel yang tepat juga bergantung pada surrender, pemeriksaan kartu tertutup, dan aturan lain.'],['Cards and points are virtual. The simulator accepts no wagers and promises no winnings.','Kartalar va ochkolar virtual. Simulyator tikishlarni qabul qilmaydi va g‘alabani va’da qilmaydi.','Кортҳо ва холҳо виртуалӣ мебошанд. Симулятор шарт қабул намекунад ва бурдро ваъда намедиҳад.','Las cartas y los puntos son virtuales. El simulador no acepta apuestas ni promete ganancias.','Kartu dan poin bersifat virtual. Simulator tidak menerima taruhan atau menjanjikan kemenangan.'],
    ['Free blackjack basic strategy trainer: make decisions, get an explanation and track your accuracy without playing for money.','Bepul Blackjack asosiy strategiya trenajyori: qaror qabul qiling, izoh oling va pulga o‘ynamasdan aniqligingizni kuzating.','Тренажёри ройгони стратегияи асосии Blackjack: қарор қабул кунед, шарҳ гиред ва дақиқии худро бе бозӣ барои пул пайгирӣ намоед.','Entrenador gratis de estrategia básica de Blackjack: tomá decisiones, recibí explicaciones y controlá tu precisión sin jugar por dinero.','Pelatih strategi dasar Blackjack gratis: ambil keputusan, dapatkan penjelasan, dan pantau akurasi tanpa bermain dengan uang.'],['Practice Hit, Stand, Double and Split decisions with instant feedback.','Karta olish, to‘xtash, ikkilash va bo‘lish qarorlarini tezkor tekshiruv bilan mashq qiling.','Қарорҳои корт гирифтан, истодан, дучанд кардан ва тақсим карданро бо санҷиши фаврӣ машқ кунед.','Practicá decisiones de Pedir, Plantarse, Doblar y Separar con respuesta inmediata.','Latih keputusan Ambil, Berhenti, Gandakan, dan Split dengan umpan balik instan.'],['Blackjack Strategy Trainer','Blackjack strategiya trenajyori','Тренажёри стратегияи Blackjack','Entrenador de estrategia de Blackjack','Pelatih strategi Blackjack'],

    ['Processed','Qayta ishlandi','Коркард шуд','Procesados','Diproses'],['of','/','аз','de','dari'],['spins…','aylantirish…','гардиш…','giros…','putaran…'],['spins','aylantirish','гардиш','giros','putaran'],['Done:','Tayyor:','Омода:','Listo:','Selesai:'],['independent spins. Theoretical model RTP:','mustaqil aylantirish. Modelning nazariy RTPsi:','гардиши мустақил. RTP-и назариявии модел:','giros independientes. RTP teórico del modelo:','putaran independen. RTP teoretis model:'],
    ['Straight number','Aniq raqam','Рақами дақиқ','Número directo','Angka langsung'],['series:','seriyasi:','силсила:','serie:','seri:'],['hits in','tushish, jami','бурд дар','aciertos en','kena dalam'],
    ['hit','karta olish','корт гирифтан','pedir','ambil'],['stand','to‘xtash','истодан','plantarse','berhenti'],['double','ikkilash','дучанд кардан','doblar','gandakan'],['split','bo‘lish','тақсим кардан','separar','split'],['Pair','Juft','Ҷуфт','Par','Pasangan'],['Soft hand','Yumshoq qo‘l','Дасти нарм','Mano blanda','Kartu lunak'],['Hard hand','Qattiq qo‘l','Дасти сахт','Mano dura','Kartu keras'],['an ace','tuz','туз','un as','ace'],['The risk of busting is lower than the expected cost of standing here.','Oshib ketish xavfi bu yerda to‘xtashning kutilayotgan zararidan pastroq.','Хатари гузаштан аз 21 аз зарари интизории истодан камтар аст.','El riesgo de pasarte es menor que el costo esperado de plantarte acá.','Risiko bust lebih rendah daripada kerugian yang diharapkan jika berhenti di sini.'],["Standing makes better use of the dealer’s weak upcard or your already strong total.",'To‘xtash dilerning kuchsiz ochiq kartasidan yoki qo‘lingizdagi kuchli yig‘indidan yaxshiroq foydalanadi.','Истодан аз корти кушодаи сусти дилер ё ҷамъбасти қавии шумо беҳтар истифода мебарад.','Plantarte aprovecha mejor la carta débil del crupier o tu total ya fuerte.','Berhenti memanfaatkan kartu terbuka dealer yang lemah atau total Anda yang sudah kuat.'],['Doubling has the best expected value in this strong starting position.','Bu kuchli boshlang‘ich vaziyatda ikkilash eng yaxshi kutilayotgan qiymatga ega.','Дар ин мавқеи қавии ибтидоӣ дучанд кардан арзиши беҳтарини интизориро дорад.','Doblar tiene el mejor valor esperado en esta posición inicial fuerte.','Menggandakan memberi nilai harapan terbaik pada posisi awal yang kuat ini.'],['Splitting this pair creates two more promising starting hands.','Bu juftni bo‘lish ikkita istiqbolli boshlang‘ich qo‘l yaratadi.','Тақсим кардани ин ҷуфт ду дасти ибтидоии умедбахштар месозад.','Separar este par crea dos manos iniciales más prometedoras.','Memisahkan pasangan ini menghasilkan dua kartu awal yang lebih menjanjikan.'],[' soft',' yumshoq',' нарм',' blanda',' lunak'],['Correct:','To‘g‘ri:','Дуруст:','Correcto:','Benar:'],['You chose','Siz tanladingiz','Шумо интихоб кардед','Elegiste','Anda memilih'],['Basic strategy recommends','Asosiy strategiya tavsiya qiladi','Стратегияи асосӣ тавсия медиҳад','La estrategia básica recomienda','Strategi dasar merekomendasikan']
  ];
  if (locale === 'en' || !order.includes(locale)) {
    window.labT = text => text;
    window.labLocale = 'en-US';
    return;
  }
  const index = order.indexOf(locale) + 1;
  const dict = new Map(rows.map(row => [row[0], row[index]]));
  const translate = text => dict.get(text) || text;
  window.labT = translate;
  window.labLocale = ({uz:'uz-UZ',tg:'tg-TJ',es:'es-AR',id:'id-ID'})[locale];
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  const keys = [...dict.keys()].sort((a,b) => b.length - a.length);
  nodes.forEach(node => {
    const raw = node.nodeValue;
    const value = raw.trim();
    if (!value) return;
    if (dict.has(value)) node.nodeValue = raw.replace(value, dict.get(value));
    else {
      const key = keys.find(item => value.includes(item));
      if (key) node.nodeValue = raw.replace(key, dict.get(key));
    }
  });
  document.querySelectorAll('[aria-label],[alt]').forEach(el => ['aria-label','alt'].forEach(attr => {
    if (el.hasAttribute(attr)) el.setAttribute(attr, translate(el.getAttribute(attr)));
  }));
  const description = document.querySelector('meta[name="description"]');
  if (description) description.setAttribute('content', translate(description.getAttribute('content')));
  const dealerHits = document.querySelector('#soft17 button[data-value="hit"]');
  if (dealerHits) dealerHits.textContent = ({uz:'Karta oladi',tg:'Корт мегирад',es:'Pide',id:'Ambil kartu'})[locale];
})();
