(() => {
  const locale = document.documentElement.lang;
  if (locale === 'ru') { window.simT = text => text; window.simLocale = 'ru-RU'; return; }
  const order = ['en', 'uz', 'tg', 'es', 'id'];
  const rows = [
    ['Образовательный симулятор','Educational simulator','Ta’limiy simulyator','Симулятори омӯзишӣ','Simulador educativo','Simulator edukatif'],
    ['Главная','Home','Bosh sahifa','Асосӣ','Inicio','Beranda'],['Статьи','Articles','Maqolalar','Мақолаҳо','Artículos','Artikel'],
    ['← Назад на главную','← Back to home','← Bosh sahifaga','← Бозгашт ба саҳифаи асосӣ','← Volver al inicio','← Kembali ke beranda'],
    ['Баланс','Balance','Balans','Тавозун','Saldo','Saldo'],['фишек','chips','fishka','фишка','fichas','chip'],
    ['Сумма ставки','Chip amount','Fishkalar miqdori','Миқдори фишкаҳо','Cantidad de fichas','Jumlah chip'],
    ['Виртуальные фишки','Virtual chips','Virtual fishkalar','Фишкаҳои виртуалӣ','Fichas virtuales','Chip virtual'],
    ['Сбросить','Reset','Qayta boshlash','Аз нав','Reiniciar','Atur ulang'],
    ['Другие игры','Other games','Boshqa o‘yinlar','Бозиҳои дигар','Otros juegos','Game lainnya'],
    ['Все игры','All games','Barcha o‘yinlar','Ҳамаи бозиҳо','Todos los juegos','Semua game'],
    ['Попробуйте другие доступные образовательные симуляторы.','Try the other available educational simulators.','Boshqa mavjud ta’limiy simulyatorlarni sinab ko‘ring.','Дигар симуляторҳои омӯзишии дастрасро санҷед.','Probá los otros simuladores educativos disponibles.','Coba simulator edukatif lain yang tersedia.'],
    ['Доступен','Available','Mavjud','Дастрас','Disponible','Tersedia'],['Играть →','Play →','O‘ynash →','Бозӣ кардан →','Jugar →','Main →'],
    ['Важно:','Important:','Muhim:','Муҳим:','Importante:','Penting:'],
    ['Коэффициент','Multiplier','Ko‘paytirgich','Зарбкунанда','Multiplicador','Pengali'],
    ['Фишки выдаются бесплатно, не продаются, не выводятся и не имеют реальной денежной ценности. Симулятор не принимает реальные ставки и не выдаёт призы.','Chips are provided free of charge, cannot be bought or withdrawn, and have no real monetary value. The simulator accepts no real bets and awards no prizes.','Fishkalar bepul beriladi, sotilmaydi, yechib olinmaydi va haqiqiy pul qiymatiga ega emas. Simulyator haqiqiy tikishlarni qabul qilmaydi va sovrin bermaydi.','Фишкаҳо ройгон дода мешаванд, фурӯхта ё бароварда намешаванд ва арзиши воқеии пулӣ надоранд. Симулятор шартҳои воқеиро қабул намекунад ва ҷоиза намедиҳад.','Las fichas son gratis, no se venden ni se retiran y no tienen valor monetario real. El simulador no acepta apuestas reales ni entrega premios.','Chip diberikan gratis, tidak dapat dibeli atau ditarik, dan tidak memiliki nilai uang nyata. Simulator tidak menerima taruhan uang asli atau memberikan hadiah.'],
    ['Основная навигация','Main navigation','Asosiy navigatsiya','Паймоиши асосӣ','Navegación principal','Navigasi utama'],['Вернуться на главную страницу','Return to home page','Bosh sahifaga qaytish','Бозгашт ба саҳифаи асосӣ','Volver al inicio','Kembali ke beranda'],['Уменьшить вдвое','Halve','Yarim qilish','Нисф кардан','Dividir por dos','Bagi dua'],['Увеличить вдвое','Double','Ikki baravar qilish','Дучанд кардан','Duplicar','Gandakan'],['Уменьшить ставку вдвое','Halve the amount','Miqdorni yarim qilish','Миқдорро нисф кардан','Dividir la cantidad por dos','Bagi jumlah menjadi dua'],['Увеличить ставку вдвое','Double the amount','Miqdorni ikki baravar qilish','Миқдорро дучанд кардан','Duplicar la cantidad','Gandakan jumlah'],
    ['Симулятор Blackjack','Blackjack simulator','Blackjack simulyatori','Симулятори Blackjack','Simulador de Blackjack','Simulator Blackjack'],['Симулятор Crazy Chicken','Crazy Chicken simulator','Crazy Chicken simulyatori','Симулятори Crazy Chicken','Simulador de Crazy Chicken','Simulator Crazy Chicken'],['Симулятор Mines','Mines simulator','Mines simulyatori','Симулятори Mines','Simulador de Mines','Simulator Mines'],['Симулятор Wheel x1000','Wheel x1000 simulator','Wheel x1000 simulyatori','Симулятори Wheel x1000','Simulador de Wheel x1000','Simulator Wheel x1000'],
    ['Обложка симулятора Plinko','Plinko simulator cover','Plinko simulyatori muqovasi','Муқоваи симулятори Plinko','Portada del simulador Plinko','Sampul simulator Plinko'],['Обложка симулятора Limbo','Limbo simulator cover','Limbo simulyatori muqovasi','Муқоваи симулятори Limbo','Portada del simulador Limbo','Sampul simulator Limbo'],['Обложка симулятора Dice','Dice simulator cover','Dice simulyatori muqovasi','Муқоваи симулятори Dice','Portada del simulador Dice','Sampul simulator Dice'],['Обложка Plinko','Plinko cover','Plinko muqovasi','Муқоваи Plinko','Portada de Plinko','Sampul Plinko'],['Обложка Limbo','Limbo cover','Limbo muqovasi','Муқоваи Limbo','Portada de Limbo','Sampul Limbo'],['Обложка Dice','Dice cover','Dice muqovasi','Муқоваи Dice','Portada de Dice','Sampul Dice'],['Обложка Blackjack','Blackjack cover','Blackjack muqovasi','Муқоваи Blackjack','Portada de Blackjack','Sampul Blackjack'],['Обложка Mines','Mines cover','Mines muqovasi','Муқоваи Mines','Portada de Mines','Sampul Mines'],['Обложка Crazy Chicken','Crazy Chicken cover','Crazy Chicken muqovasi','Муқоваи Crazy Chicken','Portada de Crazy Chicken','Sampul Crazy Chicken'],
    ['Дорога Crazy Chicken','Crazy Chicken road','Crazy Chicken yo‘li','Роҳи Crazy Chicken','Camino de Crazy Chicken','Jalan Crazy Chicken'],['Курица','Chicken','Tovuq','Мурғ','Gallina','Ayam'],['Игровое поле Mines','Mines game board','Mines o‘yin maydoni','Майдони бозии Mines','Tablero de Mines','Papan game Mines'],['Последние результаты','Recent results','So‘nggi natijalar','Натиҷаҳои охирин','Resultados recientes','Hasil terbaru'],
    ['Бесплатный образовательный симулятор Blackjack: соберите 21, изучите стоимость карт и решения дилера с виртуальными фишками.','Free educational Blackjack simulator: reach 21 and explore card values and dealer decisions with virtual chips.','Bepul Blackjack ta’limiy simulyatori: 21 ni to‘plang, karta qiymatlari va diler qarorlarini virtual fishkalar bilan o‘rganing.','Симулятори ройгони омӯзишии Blackjack: 21 ҷамъ кунед ва қимати кортҳою қарорҳои дилерро бо фишкаҳои виртуалӣ омӯзед.','Simulador educativo gratis de Blackjack: llegá a 21 y explorá el valor de las cartas y las decisiones del crupier con fichas virtuales.','Simulator edukatif Blackjack gratis: raih 21 dan pelajari nilai kartu serta keputusan dealer dengan chip virtual.'],
    ['Бесплатный образовательный симулятор Crazy Chicken: переводите курицу через дорогу, изучая риск, вероятность и рост коэффициента.','Free educational Crazy Chicken simulator: cross the road while exploring risk, probability and multiplier growth.','Bepul Crazy Chicken ta’limiy simulyatori: xavf, ehtimollik va ko‘paytirgich o‘sishini o‘rganib, tovuqni yo‘ldan olib o‘ting.','Симулятори ройгони омӯзишии Crazy Chicken: мурғро аз роҳ гузаронда, хатар, эҳтимолият ва афзоиши зарбкунандаро омӯзед.','Simulador educativo gratis de Crazy Chicken: cruzá la calle mientras explorás el riesgo, la probabilidad y el crecimiento del multiplicador.','Simulator edukatif Crazy Chicken gratis: seberangi jalan sambil mempelajari risiko, probabilitas, dan pertumbuhan pengali.'],
    ['Бесплатный образовательный симулятор Mines: открывайте кристаллы, избегайте мин и наблюдайте, как риск влияет на коэффициент.','Free educational Mines simulator: uncover crystals, avoid mines and observe how risk affects the multiplier.','Bepul Mines ta’limiy simulyatori: kristallarni oching, minalardan saqlaning va xavf ko‘paytirgichga qanday ta’sir qilishini kuzating.','Симулятори ройгони омӯзишии Mines: булӯрҳоро кушоед, аз минаҳо канорагирӣ кунед ва таъсири хатарро ба зарбкунанда бинед.','Simulador educativo gratis de Mines: descubrí cristales, evitá minas y observá cómo el riesgo afecta el multiplicador.','Simulator edukatif Mines gratis: buka kristal, hindari ranjau, dan amati pengaruh risiko pada pengali.'],
    ['Бесплатный образовательный симулятор Wheel x1000: вращайте колесо с коэффициентами от 0× до редкого 1000× и изучайте вероятности.','Free educational Wheel x1000 simulator: spin from 0× to the rare 1000× and explore probability.','Bepul Wheel x1000 ta’limiy simulyatori: 0× dan noyob 1000× gacha g‘ildirakni aylantiring va ehtimollikni o‘rganing.','Симулятори ройгони омӯзишии Wheel x1000: чархро аз 0× то 1000×-и нодир гардонда, эҳтимолиятро омӯзед.','Simulador educativo gratis de Wheel x1000: girá desde 0× hasta el raro 1000× y explorá la probabilidad.','Simulator edukatif Wheel x1000 gratis: putar dari 0× hingga 1000× yang langka dan pelajari probabilitas.'],

    ['Карты, решения и вероятность','Cards, decisions and probability','Kartalar, qarorlar va ehtimollik','Кортҳо, қарорҳо ва эҳтимолият','Cartas, decisiones y probabilidad','Kartu, keputusan, dan probabilitas'],
    ['Образовательный симулятор Blackjack','Educational Blackjack simulator','Blackjack ta’limiy simulyatori','Симулятори омӯзишии Blackjack','Simulador educativo de Blackjack','Simulator edukatif Blackjack'],
    ['Соберите комбинацию ближе к 21, чем у дилера, но не превышайте 21. Игра идёт только на бесплатные виртуальные фишки.','Build a hand closer to 21 than the dealer without going over. The game uses free virtual chips only.','21 dan oshmasdan, dilerga qaraganda 21 ga yaqinroq qo‘l to‘plang. O‘yinda faqat bepul virtual fishkalar ishlatiladi.','Дастеро ҷамъ кунед, ки аз дасти дилер ба 21 наздиктар бошад, аммо аз 21 нагузарад. Танҳо фишкаҳои виртуалии ройгон истифода мешаванд.','Armá una mano más cercana a 21 que la del crupier sin pasarte. El juego usa solamente fichas virtuales gratis.','Buat kartu yang lebih dekat ke 21 daripada dealer tanpa melewatinya. Game hanya memakai chip virtual gratis.'],
    ['Новая раздача','New deal','Yangi tarqatish','Тақсимоти нав','Nueva mano','Bagikan kartu'],['Взять карту','Hit','Karta olish','Корт гирифтан','Pedir','Ambil kartu'],['Пас','Stand','To‘xtash','Истодан','Plantarse','Berhenti'],['Удвоить','Double','Ikki baravar','Дучанд кардан','Doblar','Gandakan'],
    ['Выберите ставку и начните первую раздачу.','Choose a chip amount and start the first deal.','Fishka miqdorini tanlang va birinchi tarqatishni boshlang.','Миқдори фишкаро интихоб карда, тақсимоти аввалро оғоз кунед.','Elegí una cantidad y empezá la primera mano.','Pilih jumlah chip dan mulai pembagian pertama.'],
    ['Правило дилера:','Dealer rule:','Diler qoidasi:','Қоидаи дилер:','Regla del crupier:','Aturan dealer:'],
    ['берёт карты до 17 и останавливается на всех 17. Blackjack оплачивается 3 к 2.','draws to 17 and stands on every 17. Blackjack pays 3 to 2.','17 gacha karta oladi va har qanday 17 da to‘xtaydi. Blackjack 3 ga 2 to‘laydi.','то 17 корт мегирад ва дар ҳар гуна 17 меистад. Blackjack бо таносуби 3 ба 2 пардохт мешавад.','pide hasta 17 y se planta con cualquier 17. Blackjack paga 3 a 2.','mengambil kartu sampai 17 dan berhenti pada semua 17. Blackjack membayar 3 banding 2.'],
    ['Дилер','Dealer','Diler','Дилер','Crupier','Dealer'],['Ваша рука','Your hand','Sizning qo‘lingiz','Дасти шумо','Tu mano','Kartu Anda'],
    ['Plinko: физика случайных отскоков','Plinko: random-bounce physics','Plinko: tasodifiy sakrash fizikasi','Plinko: физикаи ҷаҳишҳои тасодуфӣ','Plinko: física de rebotes aleatorios','Plinko: fisika pantulan acak'],
    ['Запускайте шарики и наблюдайте распределение случайных результатов.','Drop balls and observe the distribution of random outcomes.','Sharlarni tashlang va tasodifiy natijalar taqsimotini kuzating.','Тӯбҳоро партоед ва тақсимоти натиҷаҳои тасодуфиро бинед.','Soltá bolas y observá la distribución de resultados aleatorios.','Jatuhkan bola dan amati distribusi hasil acak.'],
    ['Limbo: коэффициент и вероятность','Limbo: multiplier and probability','Limbo: ko‘paytirgich va ehtimollik','Limbo: зарбкунанда ва эҳтимолият','Limbo: multiplicador y probabilidad','Limbo: pengali dan probabilitas'],
    ['Выберите цель и исследуйте, как меняется вероятность результата.','Choose a target and explore how its probability changes.','Maqsadni tanlang va natija ehtimoli qanday o‘zgarishini o‘rganing.','Ҳадафро интихоб карда, тағйири эҳтимолияти натиҷаро омӯзед.','Elegí un objetivo y explorá cómo cambia la probabilidad del resultado.','Pilih target dan pelajari perubahan probabilitas hasil.'],
    ['Dice: шкала 0–100','Dice: 0–100 scale','Dice: 0–100 shkalasi','Dice: ҷадвали 0–100','Dice: escala de 0 a 100','Dice: skala 0–100'],
    ['Выберите условие и наблюдайте результат на числовой шкале.','Choose a condition and observe the result on a number scale.','Shartni tanlang va natijani raqamli shkalada kuzating.','Шартро интихоб карда, натиҷаро дар ҷадвали рақамӣ бинед.','Elegí una condición y observá el resultado en la escala numérica.','Pilih kondisi dan amati hasil pada skala angka.'],
    ['Как работает Blackjack','How Blackjack works','Blackjack qanday ishlaydi','Blackjack чӣ гуна кор мекунад','Cómo funciona Blackjack','Cara kerja Blackjack'],
    ['Числовые карты стоят по номиналу, валет, дама и король — 10, а туз — 11 или 1, если 11 приводит к перебору. После вашего решения дилер открывает скрытую карту и добирает до 17.','Number cards count at face value; jacks, queens and kings count as 10; an ace counts as 11 or 1 when 11 would cause a bust. After your decision, the dealer reveals the hidden card and draws to 17.','Raqamli kartalar o‘z qiymatiga, valet, dama va qirol 10 ga teng; tuz esa 11 yoki oshib ketishda 1 hisoblanadi. Qaroringizdan so‘ng diler yashirin kartani ochib, 17 gacha oladi.','Кортҳои рақамӣ бо қимати худ, валет, дама ва шоҳ 10 ҳисоб мешаванд; туз 11 ё ҳангоми гузаштан аз 21 як ҳисоб мешавад. Пас аз қарори шумо дилер корти пинҳониро мекушояд ва то 17 мегирад.','Las cartas numéricas valen su número; jota, reina y rey valen 10; el as vale 11 o 1 si 11 hace pasar de 21. Después de tu decisión, el crupier revela su carta oculta y pide hasta 17.','Kartu angka bernilai sesuai angkanya; jack, queen, dan king bernilai 10; ace bernilai 11 atau 1 jika 11 membuat bust. Setelah keputusan Anda, dealer membuka kartu tersembunyi dan mengambil kartu hingga 17.'],

    ['Решение, риск и следующий шаг','Decision, risk and the next step','Qaror, xavf va keyingi qadam','Қарор, хатар ва қадами навбатӣ','Decisión, riesgo y próximo paso','Keputusan, risiko, dan langkah berikutnya'],
    ['Образовательный симулятор Crazy Chicken','Educational Crazy Chicken simulator','Crazy Chicken ta’limiy simulyatori','Симулятори омӯзишии Crazy Chicken','Simulador educativo de Crazy Chicken','Simulator edukatif Crazy Chicken'],
    ['Переведите курицу через оживлённую дорогу. Каждый безопасный шаг повышает коэффициент, но вместе с ним растёт цена следующего решения.','Guide the chicken across a busy road. Every safe step raises the multiplier—and the stakes of your next decision.','Tovuqni serqatnov yo‘ldan olib o‘ting. Har bir xavfsiz qadam ko‘paytirgichni va keyingi qaror narxini oshiradi.','Мурғро аз роҳи серҳаракат гузаронед. Ҳар қадами бехатар зарбкунанда ва аҳамияти қарори навбатиро зиёд мекунад.','Ayudá a la gallina a cruzar una calle transitada. Cada paso seguro aumenta el multiplicador y el peso de la próxima decisión.','Bantu ayam menyeberangi jalan yang ramai. Setiap langkah aman menaikkan pengali sekaligus risiko keputusan berikutnya.'],
    ['Уровень сложности','Difficulty','Qiyinlik darajasi','Сатҳи душворӣ','Dificultad','Tingkat kesulitan'],['Риск 16%','Risk 16%','Xavf 16%','Хатар 16%','Riesgo 16%','Risiko 16%'],
    ['Лёгкий','Easy','Oson','Осон','Fácil','Mudah'],['Средний','Medium','O‘rtacha','Миёна','Medio','Sedang'],['Сложный','Hard','Qiyin','Душвор','Difícil','Sulit'],['Безумный','Crazy','Juda qiyin','Девонавор','Extremo','Ekstrem'],
    ['Начать переход','Start crossing','O‘tishni boshlash','Гузаришро оғоз кардан','Empezar a cruzar','Mulai menyeberang'],['Забрать ·','Collect ·','Olish ·','Гирифтан ·','Cobrar ·','Ambil ·'],['Вперёд','Forward','Oldinga','Ба пеш','Avanzar','Maju'],['Пройдено','Steps','Qadamlar','Қадамҳо','Avance','Langkah'],
    ['Выберите ставку и уровень сложности.','Choose a chip amount and difficulty.','Fishka miqdori va qiyinlik darajasini tanlang.','Миқдори фишка ва сатҳи душвориро интихоб кунед.','Elegí una cantidad y la dificultad.','Pilih jumlah chip dan tingkat kesulitan.'],
    ['это учебная модель со случайным исходом. Используются только бесплатные виртуальные фишки.','this is an educational model with random outcomes. Only free virtual chips are used.','bu tasodifiy natijali ta’limiy model. Faqat bepul virtual fishkalar ishlatiladi.','ин модели омӯзишӣ бо натиҷаи тасодуфӣ аст. Танҳо фишкаҳои виртуалии ройгон истифода мешаванд.','este es un modelo educativo con resultados aleatorios. Solo se usan fichas virtuales gratis.','ini adalah model edukatif dengan hasil acak. Hanya chip virtual gratis yang digunakan.'],
    ['СТАРТ','START','START','ОҒОЗ','INICIO','MULAI'],['Начните переход','Start crossing','O‘tishni boshlang','Гузаришро оғоз кунед','Empezá a cruzar','Mulai menyeberang'],['ФИНИШ','FINISH','FINISH','МАРРА','META','FINIS'],['безопасный шаг','safe step','xavfsiz qadam','қадами бехатар','paso seguro','langkah aman'],['Шанс пройти следующий шаг: 84%','Chance of passing the next step: 84%','Keyingi qadamdan o‘tish ehtimoli: 84%','Имкони гузаштани қадами навбатӣ: 84%','Probabilidad de superar el próximo paso: 84%','Peluang melewati langkah berikutnya: 84%'],['автомобиль','vehicle','avtomobil','мошин','vehículo','kendaraan'],
    ['Случайные отскоки.','Random bounces.','Tasodifiy sakrashlar.','Ҷаҳишҳои тасодуфӣ.','Rebotes aleatorios.','Pantulan acak.'],['Цель и вероятность.','Target and probability.','Maqsad va ehtimollik.','Ҳадаф ва эҳтимолият.','Objetivo y probabilidad.','Target dan probabilitas.'],['Шкала 0–100.','0–100 scale.','0–100 shkalasi.','Ҷадвали 0–100.','Escala de 0 a 100.','Skala 0–100.'],['Соберите 21.','Build to 21.','21 ni to‘plang.','21 ҷамъ кунед.','Llegá a 21.','Raih 21.'],['Кристаллы и риск.','Crystals and risk.','Kristallar va xavf.','Булӯрҳо ва хатар.','Cristales y riesgo.','Kristal dan risiko.'],
    ['Как работает Crazy Chicken','How Crazy Chicken works','Crazy Chicken qanday ishlaydi','Crazy Chicken чӣ гуна кор мекунад','Cómo funciona Crazy Chicken','Cara kerja Crazy Chicken'],
    ['Дорога состоит из семи независимых шагов. Кнопка «Вперёд» моделирует очередное решение: курица либо безопасно достигает следующей позиции, либо встречает автомобиль, и раунд заканчивается.','The road has seven independent steps. The Forward button models each decision: the chicken either reaches the next position safely or meets a vehicle and ends the round.','Yo‘l yetti mustaqil qadamdan iborat. “Oldinga” tugmasi har bir qarorni modellashtiradi: tovuq keyingi joyga xavfsiz yetadi yoki avtomobilga duch kelib, raund tugaydi.','Роҳ аз ҳафт қадами мустақил иборат аст. Тугмаи «Ба пеш» ҳар қарорро модел мекунад: мурғ ё ба мавқеи навбатӣ бехатар мерасад ё бо мошин бархӯрда, давр анҷом меёбад.','El camino tiene siete pasos independientes. El botón Avanzar modela cada decisión: la gallina llega segura a la próxima posición o se cruza con un vehículo y termina la ronda.','Jalan terdiri dari tujuh langkah independen. Tombol Maju memodelkan setiap keputusan: ayam tiba dengan aman di posisi berikutnya atau tertabrak kendaraan dan ronde berakhir.'],
    ['На лёгком уровне вероятность опасности на каждом шаге ниже, а коэффициенты растут медленнее. На сложных уровнях риск выше, поэтому безопасный переход увеличивает возможный результат сильнее. После любого успешного шага результат можно забрать.','On Easy, danger is less likely at each step and multipliers grow more slowly. Harder levels have more risk, so a safe crossing raises the potential result faster. You can collect after any successful step.','Oson darajada har qadamdagi xavf kamroq va ko‘paytirgichlar sekinroq o‘sadi. Qiyin darajalarda xavf yuqori, shuning uchun xavfsiz qadam mumkin bo‘lgan natijani tezroq oshiradi. Har bir muvaffaqiyatli qadamdan so‘ng natijani olish mumkin.','Дар сатҳи осон хатар дар ҳар қадам камтар ва зарбкунандаҳо сусттар меафзоянд. Дар сатҳҳои душвор хатар зиёдтар аст, бинобар ин қадами бехатар натиҷаи имконпазирро тезтар зиёд мекунад. Пас аз ҳар қадами муваффақ натиҷаро гирифтан мумкин аст.','En Fácil hay menos peligro por paso y los multiplicadores crecen más lento. En niveles difíciles hay más riesgo, así que un paso seguro aumenta más rápido el resultado posible. Podés cobrar después de cualquier paso exitoso.','Pada tingkat Mudah, bahaya lebih kecil dan pengali tumbuh lebih lambat. Tingkat yang lebih sulit memiliki risiko lebih tinggi, sehingga langkah aman menaikkan potensi hasil lebih cepat. Anda dapat mengambil hasil setelah langkah berhasil.'],

    ['Риск, вероятность и выбор','Risk, probability and choice','Xavf, ehtimollik va tanlov','Хатар, эҳтимолият ва интихоб','Riesgo, probabilidad y elección','Risiko, probabilitas, dan pilihan'],
    ['Образовательный симулятор Mines','Educational Mines simulator','Mines ta’limiy simulyatori','Симулятори омӯзишии Mines','Simulador educativo de Mines','Simulator edukatif Mines'],
    ['Открывайте безопасные клетки и забирайте виртуальные фишки вовремя. Чем больше мин и найденных кристаллов, тем выше коэффициент — и риск.','Open safe cells and collect virtual chips in time. More mines and discovered crystals mean a higher multiplier—and more risk.','Xavfsiz kataklarni oching va virtual fishkalarni vaqtida oling. Minalar va topilgan kristallar qancha ko‘p bo‘lsa, ko‘paytirgich va xavf shuncha yuqori bo‘ladi.','Ҳуҷайраҳои бехатарро кушоед ва фишкаҳои виртуалиро сари вақт гиред. Минаҳо ва булӯрҳои ёфтшуда ҳар қадар зиёд бошанд, зарбкунанда ва хатар ҳамон қадар баланд мешаванд.','Abrí casillas seguras y cobrá las fichas virtuales a tiempo. Cuantas más minas y cristales encuentres, mayor será el multiplicador y el riesgo.','Buka kotak aman dan ambil chip virtual tepat waktu. Makin banyak ranjau dan kristal ditemukan, makin tinggi pengali dan risikonya.'],
    ['Количество мин','Number of mines','Minalar soni','Шумораи минаҳо','Cantidad de minas','Jumlah ranjau'],['22 кристалла','22 crystals','22 kristall','22 булӯр','22 cristales','22 kristal'],['Начать игру','Start game','O‘yinni boshlash','Оғози бозӣ','Empezar','Mulai game'],['Случайный выбор','Random pick','Tasodifiy tanlov','Интихоби тасодуфӣ','Elección aleatoria','Pilih acak'],['Открыто','Opened','Ochildi','Кушода','Abiertas','Terbuka'],
    ['Выберите ставку и количество мин.','Choose a chip amount and number of mines.','Fishka miqdori va minalar sonini tanlang.','Миқдори фишка ва шумораи минаҳоро интихоб кунед.','Elegí una cantidad y el número de minas.','Pilih jumlah chip dan ranjau.'],
    ['симулятор использует только бесплатные фишки. Расположение мин создаётся заново в каждом раунде.','the simulator uses free chips only. Mine positions are generated anew each round.','simulyator faqat bepul fishkalardan foydalanadi. Minalar joylashuvi har raundda yangidan yaratiladi.','симулятор танҳо фишкаҳои ройгонро истифода мебарад. Ҷойгиршавии минаҳо дар ҳар давр аз нав сохта мешавад.','el simulador usa solamente fichas gratis. Las minas se ubican de nuevo en cada ronda.','simulator hanya memakai chip gratis. Posisi ranjau dibuat ulang setiap ronde.'],
    ['ПОЛЕ 5 × 5','5 × 5 BOARD','5 × 5 MAYDON','МАЙДОНИ 5 × 5','TABLERO 5 × 5','PAPAN 5 × 5'],['Начните игру, чтобы открыть клетки','Start a game to open cells','Kataklarni ochish uchun o‘yinni boshlang','Барои кушодани ҳуҷайраҳо бозиро оғоз кунед','Empezá para abrir casillas','Mulai game untuk membuka kotak'],['Вероятность безопасного первого выбора:','Probability of a safe first pick:','Birinchi xavfsiz tanlov ehtimoli:','Эҳтимолияти интихоби аввали бехатар:','Probabilidad de una primera elección segura:','Peluang pilihan pertama aman:'],
    ['Plinko: случайные отскоки','Plinko: random bounces','Plinko: tasodifiy sakrashlar','Plinko: ҷаҳишҳои тасодуфӣ','Plinko: rebotes aleatorios','Plinko: pantulan acak'],['Наблюдайте распределение случайных результатов.','Observe the distribution of random outcomes.','Tasodifiy natijalar taqsimotini kuzating.','Тақсимоти натиҷаҳои тасодуфиро бинед.','Observá la distribución de resultados aleatorios.','Amati distribusi hasil acak.'],['Limbo: коэффициент','Limbo: multiplier','Limbo: ko‘paytirgich','Limbo: зарбкунанда','Limbo: multiplicador','Limbo: pengali'],['Исследуйте связь цели и вероятности.','Explore the link between target and probability.','Maqsad va ehtimollik bog‘liqligini o‘rganing.','Робитаи ҳадаф ва эҳтимолиятро омӯзед.','Explorá la relación entre objetivo y probabilidad.','Pelajari hubungan target dan probabilitas.'],['Проверяйте условия на числовой шкале.','Test conditions on a number scale.','Shartlarni raqamli shkalada tekshiring.','Шартҳоро дар ҷадвали рақамӣ санҷед.','Probá condiciones en una escala numérica.','Uji kondisi pada skala angka.'],['Blackjack: соберите 21','Blackjack: build to 21','Blackjack: 21 ni to‘plang','Blackjack: 21 ҷамъ кунед','Blackjack: llegá a 21','Blackjack: raih 21'],['Считайте очки и сравнивайте руки.','Count points and compare hands.','Ballarni hisoblang va qo‘llarni solishtiring.','Холҳоро ҳисоб карда, дастҳоро муқоиса кунед.','Contá puntos y compará manos.','Hitung poin dan bandingkan kartu.'],
    ['Как работает Mines','How Mines works','Mines qanday ishlaydi','Mines чӣ гуна кор мекунад','Cómo funciona Mines','Cara kerja Mines'],
    ['В начале раунда мины случайно размещаются под 25 клетками. Каждый найденный кристалл уменьшает число оставшихся безопасных клеток и увеличивает коэффициент. Можно забрать результат после любого успешного выбора или продолжить ради более высокого множителя.','At the start of a round, mines are randomly placed under 25 cells. Every crystal found reduces the safe cells remaining and raises the multiplier. Collect after any successful pick or continue for a higher multiplier.','Raund boshida minalar 25 katak ostiga tasodifiy joylashtiriladi. Har bir topilgan kristall qolgan xavfsiz kataklar sonini kamaytiradi va ko‘paytirgichni oshiradi. Har qanday muvaffaqiyatli tanlovdan so‘ng natijani oling yoki yuqori ko‘paytirgich uchun davom eting.','Дар оғози давр минаҳо ба таври тасодуфӣ зери 25 ҳуҷайра ҷойгир мешаванд. Ҳар булӯри ёфтшуда шумораи ҳуҷайраҳои бехатари боқимондаро кам ва зарбкунандаро зиёд мекунад. Пас аз ҳар интихоби муваффақ натиҷаро гиред ё барои зарбкунандаи баландтар идома диҳед.','Al comenzar la ronda, las minas se distribuyen al azar bajo 25 casillas. Cada cristal reduce las casillas seguras restantes y aumenta el multiplicador. Podés cobrar después de cualquier elección exitosa o seguir por un multiplicador mayor.','Di awal ronde, ranjau ditempatkan secara acak di bawah 25 kotak. Setiap kristal mengurangi kotak aman yang tersisa dan menaikkan pengali. Ambil hasil setelah pilihan berhasil atau lanjutkan demi pengali lebih tinggi.'],
    ['Коэффициент рассчитан из вероятности последовательно открыть безопасные клетки с небольшим учебным запасом 3%. Например, при 3 минах шанс первого безопасного выбора равен 22 из 25, или 88%.','The multiplier is based on the probability of opening safe cells in sequence, with a small 3% educational margin. With 3 mines, for example, the first safe-pick chance is 22 out of 25, or 88%.','Ko‘paytirgich xavfsiz kataklarni ketma-ket ochish ehtimoli va kichik 3% ta’limiy zaxira asosida hisoblanadi. Masalan, 3 ta minada birinchi xavfsiz tanlov ehtimoli 25 dan 22 yoki 88%.','Зарбкунанда аз эҳтимолияти пайдарпай кушодани ҳуҷайраҳои бехатар бо захираи хурди омӯзишии 3% ҳисоб мешавад. Масалан, бо 3 мина имкони интихоби аввали бехатар 22 аз 25 ё 88% аст.','El multiplicador se calcula según la probabilidad de abrir casillas seguras en secuencia, con un pequeño margen educativo del 3%. Con 3 minas, por ejemplo, la primera elección segura tiene una probabilidad de 22 sobre 25, o 88%.','Pengali dihitung dari peluang membuka kotak aman secara berurutan, dengan margin edukatif kecil 3%. Contohnya, dengan 3 ranjau peluang pilihan aman pertama adalah 22 dari 25, atau 88%.'],

    ['Редкий сектор и большие числа','A rare sector and big numbers','Noyob sektor va katta sonlar','Бахши нодир ва рақамҳои калон','Un sector raro y números grandes','Sektor langka dan angka besar'],
    ['Образовательный симулятор Wheel x1000','Educational Wheel x1000 simulator','Wheel x1000 ta’limiy simulyatori','Симулятори омӯзишии Wheel x1000','Simulador educativo de Wheel x1000','Simulator edukatif Wheel x1000'],
    ['Запустите колесо с коэффициентами от 0× до редкого 1000× и наблюдайте, как вероятность влияет на возможный результат.','Spin a wheel with multipliers from 0× to the rare 1000× and observe how probability affects the potential result.','0× dan noyob 1000× gacha ko‘paytirgichli g‘ildirakni aylantiring va ehtimollik mumkin bo‘lgan natijaga qanday ta’sir qilishini kuzating.','Чархро бо зарбкунандаҳои аз 0× то 1000×-и нодир гардонед ва таъсири эҳтимолиятро ба натиҷаи имконпазир бинед.','Girá una rueda con multiplicadores de 0× al raro 1000× y observá cómo la probabilidad afecta el resultado posible.','Putar roda dengan pengali dari 0× hingga 1000× yang langka dan amati pengaruh probabilitas pada potensi hasil.'],
    ['Ручной режим','Manual mode','Qo‘lda','Дастӣ','Modo manual','Mode manual'],['Авто','Auto','Avto','Авто','Auto','Otomatis'],['Крутить колесо','Spin wheel','G‘ildirakni aylantirish','Чархро гардондан','Girar la rueda','Putar roda'],['Последний результат','Last result','So‘nggi natija','Натиҷаи охирин','Último resultado','Hasil terakhir'],['Выплата','Payout','To‘lov','Пардохт','Pago','Pembayaran'],['Выберите ставку и запустите колесо.','Choose a chip amount and spin the wheel.','Fishka miqdorini tanlang va g‘ildirakni aylantiring.','Миқдори фишкаро интихоб карда, чархро гардонед.','Elegí una cantidad y girá la rueda.','Pilih jumlah chip dan putar roda.'],['Математика:','Math:','Matematika:','Математика:','Matemática:','Matematika:'],['шанс ×1000 — 0,05%, или 1 из 2000 вращений. Теоретическая отдача всей модели — 97%.','the chance of ×1000 is 0.05%, or 1 in 2,000 spins. The theoretical return of the model is 97%.','×1000 ehtimoli 0,05%, ya’ni 2000 aylantirishdan 1 tasi. Modelning nazariy qaytishi 97%.','имкони ×1000 — 0,05% ё 1 аз 2000 гардиш. Бозгашти назариявии модел 97% аст.','la probabilidad de ×1000 es 0,05%, o 1 en 2000 giros. El retorno teórico del modelo es 97%.','peluang ×1000 adalah 0,05%, atau 1 dari 2.000 putaran. Pengembalian teoretis model adalah 97%.'],
    ['Как работает Wheel x1000','How Wheel x1000 works','Wheel x1000 qanday ishlaydi','Wheel x1000 чӣ гуна кор мекунад','Cómo funciona Wheel x1000','Cara kerja Wheel x1000'],
    ['Каждое вращение выбирает результат согласно фиксированному распределению: 0× — 78,9%; 1,5× — 8%; 1,7× — 4%; 2× — 3%; 3× — 2%; 4× — 4,05%; 1000× — 0,05%. В сумме это даёт теоретическую отдачу 97%.','Each spin selects an outcome from a fixed distribution: 0× — 78.9%; 1.5× — 8%; 1.7× — 4%; 2× — 3%; 3× — 2%; 4× — 4.05%; 1000× — 0.05%. Together, this gives a 97% theoretical return.','Har aylantirish qat’iy taqsimot bo‘yicha natijani tanlaydi: 0× — 78,9%; 1,5× — 8%; 1,7× — 4%; 2× — 3%; 3× — 2%; 4× — 4,05%; 1000× — 0,05%. Jami nazariy qaytish 97%.','Ҳар гардиш натиҷаро аз рӯи тақсимоти собит интихоб мекунад: 0× — 78,9%; 1,5× — 8%; 1,7× — 4%; 2× — 3%; 3× — 2%; 4× — 4,05%; 1000× — 0,05%. Дар маҷмӯъ бозгашти назариявӣ 97% аст.','Cada giro elige un resultado según una distribución fija: 0× — 78,9%; 1,5× — 8%; 1,7× — 4%; 2× — 3%; 3× — 2%; 4× — 4,05%; 1000× — 0,05%. En total da un retorno teórico del 97%.','Setiap putaran memilih hasil menurut distribusi tetap: 0× — 78,9%; 1,5× — 8%; 1,7× — 4%; 2× — 3%; 3× — 2%; 4× — 4,05%; 1000× — 0,05%. Total pengembalian teoretisnya 97%.'],
    ['Редкий сектор ×1000 выпадает в среднем один раз на 2000 независимых вращений. Это средняя частота на очень длинной дистанции, а не обещание результата через определённое число запусков.','The rare ×1000 sector appears once per 2,000 independent spins on average. This is a long-run average, not a promise that it will appear after a certain number of spins.','Noyob ×1000 sektor o‘rtacha 2000 mustaqil aylantirishda bir marta tushadi. Bu juda uzoq muddatli o‘rtacha ko‘rsatkich, ma’lum aylantirish sonidan keyingi natija va’dasi emas.','Бахши нодири ×1000 ба ҳисоби миёна як бор дар 2000 гардиши мустақил меафтад. Ин басомади миёна дар масофаи хеле дароз аст, на ваъдаи натиҷа пас аз шумораи муайяни гардишҳо.','El sector raro ×1000 aparece en promedio una vez cada 2000 giros independientes. Es una frecuencia media a muy largo plazo, no una promesa tras cierta cantidad de giros.','Sektor langka ×1000 rata-rata muncul sekali dalam 2.000 putaran independen. Ini adalah rata-rata jangka sangat panjang, bukan janji hasil setelah jumlah putaran tertentu.'],

    ['Закрытая карта','Hidden card','Yopiq karta','Корти пӯшида','Carta oculta','Kartu tertutup'],
    ['<strong>Blackjack!</strong> Выплата 3 к 2.','<strong>Blackjack!</strong> Pays 3 to 2.','<strong>Blackjack!</strong> 3 ga 2 to‘laydi.','<strong>Blackjack!</strong> Пардохт 3 ба 2.','<strong>¡Blackjack!</strong> Paga 3 a 2.','<strong>Blackjack!</strong> Membayar 3 banding 2.'],
    ['<strong>Победа.</strong> Ваша рука сильнее.','<strong>Win.</strong> Your hand is stronger.','<strong>G‘alaba.</strong> Qo‘lingiz kuchliroq.','<strong>Ғалаба.</strong> Дасти шумо қавитар аст.','<strong>Ganaste.</strong> Tu mano es mejor.','<strong>Menang.</strong> Kartu Anda lebih kuat.'],
    ['<strong>Поражение.</strong> В этот раз сильнее дилер.','<strong>Loss.</strong> The dealer is stronger this time.','<strong>Mag‘lubiyat.</strong> Bu safar diler kuchliroq.','<strong>Бохт.</strong> Ин дафъа дилер қавитар аст.','<strong>Perdiste.</strong> Esta vez gana el crupier.','<strong>Kalah.</strong> Kali ini dealer lebih kuat.'],
    ['<strong>Ничья.</strong> Ставка возвращена.','<strong>Push.</strong> Your chips are returned.','<strong>Durrang.</strong> Fishkalar qaytarildi.','<strong>Мусовӣ.</strong> Фишкаҳо баргардонида шуданд.','<strong>Empate.</strong> Se devuelven las fichas.','<strong>Seri.</strong> Chip dikembalikan.'],
    ['Недостаточно виртуальных фишек для этой ставки.','Not enough virtual chips for this amount.','Bu miqdor uchun virtual fishkalar yetarli emas.','Барои ин миқдор фишкаҳои виртуалӣ намерасанд.','No hay suficientes fichas virtuales para esa cantidad.','Chip virtual tidak cukup untuk jumlah ini.'],
    ['Ваш ход: возьмите карту, остановитесь или удвойте ставку.','Your turn: hit, stand, or double.','Navbatingiz: karta oling, to‘xtang yoki ikki baravar qiling.','Навбати шумо: корт гиред, истед ё дучанд кунед.','Tu turno: pedí, plantate o doblá.','Giliran Anda: ambil kartu, berhenti, atau gandakan.'],
    ['Баланс восстановлен. Выберите ставку и начните раздачу.','Balance restored. Choose an amount and start a deal.','Balans tiklandi. Miqdorni tanlang va tarqatishni boshlang.','Тавозун барқарор шуд. Миқдорро интихоб карда, тақсимотро оғоз кунед.','Saldo restaurado. Elegí una cantidad y empezá una mano.','Saldo dipulihkan. Pilih jumlah dan mulai pembagian.'],
    ['Риск','Risk','Xavf','Хатар','Riesgo','Risiko'],['Шанс пройти следующий шаг:','Chance of passing the next step:','Keyingi qadamdan o‘tish ehtimoli:','Имкони гузаштани қадами навбатӣ:','Probabilidad de superar el próximo paso:','Peluang melewati langkah berikutnya:'],
    ['Введите ставку от 1 до доступного баланса.','Enter an amount from 1 up to your available balance.','1 dan mavjud balansgacha miqdor kiriting.','Миқдореро аз 1 то тавозуни дастрас ворид кунед.','Ingresá una cantidad entre 1 y el saldo disponible.','Masukkan jumlah dari 1 hingga saldo yang tersedia.'],
    ['Двигайтесь вперёд или заберите результат','Move forward or collect the result','Oldinga yuring yoki natijani oling','Ба пеш равед ё натиҷаро гиред','Avanzá o cobrá el resultado','Maju atau ambil hasil'],['Столкновение — раунд завершён','Collision — round over','To‘qnashuv — raund tugadi','Бархӯрд — давр анҷом ёфт','Choque: ronda terminada','Tabrakan — ronde berakhir'],['Автомобиль! Ставка потеряна. Попробуйте другой уровень риска.','Vehicle! The chips are lost. Try another risk level.','Avtomobil! Fishkalar yo‘qotildi. Boshqa xavf darajasini sinang.','Мошин! Фишкаҳо аз даст рафтанд. Сатҳи дигари хатарро санҷед.','¡Vehículo! Perdiste las fichas. Probá otro nivel de riesgo.','Kendaraan! Chip hilang. Coba tingkat risiko lain.'],['Шаг пройден! Можно забрать','Step cleared! You can collect','Qadam o‘tildi! Olishingiz mumkin','Қадам гузашт! Метавонед гиред','¡Paso superado! Podés cobrar','Langkah berhasil! Anda dapat mengambil'],['или идти дальше.','or keep going.','yoki davom eting.','ё идома диҳед.','o seguir.','atau lanjutkan.'],['Финиш достигнут!','Finish reached!','Marraga yetdingiz!','Ба марра расидед!','¡Llegaste a la meta!','Berhasil mencapai finis!'],['Результат сохранён','Result collected','Natija olindi','Натиҷа гирифта шуд','Resultado cobrado','Hasil diambil'],['Дорога пройдена! ','Road crossed! ','Yo‘l o‘tildi! ','Роҳ гузашт! ','¡Cruzaste la calle! ','Jalan berhasil diseberangi! '],['Результат забран. ','Result collected. ','Natija olindi. ','Натиҷа гирифта шуд. ','Resultado cobrado. ','Hasil diambil. '],['Начислено','Awarded','Berildi','Ҳисоб шуд','Se acreditaron','Diberikan'],['Баланс восстановлен. Выберите параметры нового перехода.','Balance restored. Choose settings for a new crossing.','Balans tiklandi. Yangi o‘tish parametrlarini tanlang.','Тавозун барқарор шуд. Танзимоти гузариши навро интихоб кунед.','Saldo restaurado. Elegí la configuración del nuevo cruce.','Saldo dipulihkan. Pilih pengaturan penyeberangan baru.'],
    ['кристаллов','crystals','kristall','булӯр','cristales','kristal'],['Вероятность следующего безопасного выбора:','Probability of the next safe pick:','Keyingi xavfsiz tanlov ehtimoli:','Эҳтимолияти интихоби навбатии бехатар:','Probabilidad de la próxima elección segura:','Peluang pilihan aman berikutnya:'],['Выберите закрытую клетку','Choose a closed cell','Yopiq katakni tanlang','Ҳуҷайраи пӯшидаро интихоб кунед','Elegí una casilla cerrada','Pilih kotak tertutup'],['Закрытая клетка','Closed cell','Yopiq katak','Ҳуҷайраи пӯшида','Casilla cerrada','Kotak tertutup'],['Раунд начат. Найдите первый кристалл.','Round started. Find the first <strong>crystal</strong>.','Raund boshlandi. Birinchi <strong>kristallni</strong> toping.','Давр оғоз шуд. <strong>Булӯри</strong> аввалро ёбед.','Ronda iniciada. Encontrá el primer <strong>cristal</strong>.','Ronde dimulai. Temukan <strong>kristal</strong> pertama.'],['Кристалл найден! Можно забрать','Crystal found! You can collect','Kristall topildi! Olishingiz mumkin','Булӯр ёфт шуд! Метавонед гиред','¡Cristal encontrado! Podés cobrar','Kristal ditemukan! Anda dapat mengambil'],['или продолжить.','or continue.','yoki davom eting.','ё идома диҳед.','o continuar.','atau lanjutkan.'],['Мина! Ставка потеряна. Все мины показаны на поле.','Mine! The chips are lost. All mines are shown on the board.','Mina! Fishkalar yo‘qotildi. Barcha minalar maydonda ko‘rsatildi.','Мина! Фишкаҳо аз даст рафтанд. Ҳамаи минаҳо дар майдон нишон дода шуданд.','¡Mina! Perdiste las fichas. Se muestran todas las minas.','Ranjau! Chip hilang. Semua ranjau ditampilkan di papan.'],['Раунд завершён','Round over','Raund tugadi','Давр анҷом ёфт','Ronda terminada','Ronde berakhir'],['Все кристаллы открыты! ','All crystals opened! ','Barcha kristallar ochildi! ','Ҳамаи булӯрҳо кушода шуданд! ','¡Abriste todos los cristales! ','Semua kristal terbuka! '],['Баланс восстановлен. Выберите параметры нового раунда.','Balance restored. Choose settings for a new round.','Balans tiklandi. Yangi raund parametrlarini tanlang.','Тавозун барқарор шуд. Танзимоти даври навро интихоб кунед.','Saldo restaurado. Elegí la configuración de una nueva ronda.','Saldo dipulihkan. Pilih pengaturan ronde baru.'],
    ['Колесо ускоряется…','The wheel is speeding up…','G‘ildirak tezlashmoqda…','Чарх суръат мегирад…','La rueda está acelerando…','Roda makin cepat…'],['Редкий сектор','Rare sector','Noyob sektor','Бахши нодир','Sector raro','Sektor langka'],['Выпало','Result:','Natija:','Натиҷа:','Salió','Hasil:'],['Выплаты нет.','No payout.','To‘lov yo‘q.','Пардохт нест.','Sin pago.','Tidak ada pembayaran.'],['Остановить','Stop','To‘xtatish','Боздоштан','Detener','Berhenti'],['Баланс восстановлен. Можно запустить колесо.','Balance restored. You can spin the wheel.','Balans tiklandi. G‘ildirakni aylantirishingiz mumkin.','Тавозун барқарор шуд. Метавонед чархро гардонед.','Saldo restaurado. Ya podés girar la rueda.','Saldo dipulihkan. Anda dapat memutar roda.']
  ];
  const index = order.indexOf(locale) + 1;
  const dict = new Map(rows.map(row => [row[0], row[index]]));
  const translate = text => dict.get(text) || text;
  window.simT = translate;
  window.simLocale = ({en:'en-US',uz:'uz-UZ',tg:'tg-TJ',es:'es-AR',id:'id-ID'})[locale] || 'ru-RU';
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT);
  const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
  const keys=[...dict.keys()].sort((a,b)=>b.length-a.length);
  nodes.forEach(node => { const raw=node.nodeValue, value=raw.trim(); if (!value) return; if (dict.has(value)) node.nodeValue=raw.replace(value,dict.get(value)); else { const key=keys.find(item=>value.includes(item)); if(key) node.nodeValue=raw.replace(key,dict.get(key)); } });
  document.querySelectorAll('[aria-label],[alt]').forEach(el => ['aria-label','alt'].forEach(attr => { if(el.hasAttribute(attr)) el.setAttribute(attr,translate(el.getAttribute(attr))); }));
})();
